---

- name: 'Reset installation'
  hosts: 'all'
  become: true
  gather_facts: true

  tasks:
    - name: 'uninstall docker & kubernetes'
      apt:
        name: '{{ item }}'
        state: 'absent'
      with_items:
        - 'kubectl'
        - 'kubeadm'
        - 'kubelet'
        - 'docker.io'

    - file:
        path: "{{ item }}"
        state: 'absent'
      with_items:
        - '/etc/kubernetes'
        - '/etc/kubectl'
        - '/etc/kubeadm-join.sh'
        - '/var/lib/etcd'
