---

- name: 'Setup pmav99 user'
  hosts: 'all'
  become: true
  gather_facts: true
  vars:
    addme_username: 'pmav99'
    addme_directory: 'zsh_remote'
  roles:
    - role: 'pmav99.addme'

- name: 'Prepare VMs'
  hosts: 'all'
  become: true
  gather_facts: false
  roles:
    - role: 'prepare'
      tags: 'prepare'

- name: 'Initialize master'
  hosts: 'masters'
  become: true
  gather_facts: false
  roles:
    - role: 'master'
      tags: 'master'

- name: 'Setup nodes'
  hosts: 'all'
  become: true
  gather_facts: false
  vars:
    master_hostname: "{{ groups['masters'][0] }}"
  roles:
    - role: 'nodes'
      tags: 'nodes'
