---

- name: 'Set ipv4 IP forwarding'
  sysctl:
    name: 'net.ipv4.ip_forward'
    value: 1
    state: 'present'
    reload: true
    sysctl_set: true
  become: true

- name: 'Start docker'
  service:
    name: 'docker'
    state: 'started'
    enabled: true
  become: true

- name: 'Start NTP'
  service:
    name: 'ntp'
    state: 'started'
    enabled: true
  become: true

- name: 'Start kubelet'
  service:
    name: 'kubelet'
    state: 'started'
    enabled: true
  become: true
