---

- name: ''
  sysctl:
    name: 'net.bridge.bridge-nf-call-ip6tables'
    value: 1
    state: 'present'
    reload: true
    sysctl_set: true
  become: true

- name: ''
  sysctl:
    name: 'net.bridge.bridge-nf-call-iptables'
    value: 1
    state: 'present'
    reload: true
    sysctl_set: true
  become: true

- name: ''
  shell: "cat /etc/kubeadm-join.sh"
  register: 'cat_kubeadm_join'
  when: inventory_hostname == master_hostname
  become: true

- set_fact:
    kubeadm_join: "{{cat_kubeadm_join.stdout}}"
  when: inventory_hostname == master_hostname
  become: true

- name: 'Join nodes'
  shell: >
     systemctl stop kubelet ; yes | kubeadm reset ;
     echo "{{hostvars[master_hostname].kubeadm_join}}" >/etc/kubeadm-join.sh ;
     bash /etc/kubeadm-join.sh
  args:
    creates: '/etc/kubeadm-join.sh'
  when: inventory_hostname != master_hostname
  become: true

- name: 'Ensure that all nodes are up'
  shell: >
      export KUBECONFIG=/etc/kubernetes/admin.conf ;
      kubectl get nodes {{item}}
  register: 'result'
  until: result.stdout.find("Ready") != -1
  retries: 100
  delay: 10
  with_items:
    - '{{ groups["nodes"] }}'
  when: inventory_hostname == master_hostname
  become: true
